export const students = [
  {
    id: 1,
    name: "Aarav Mehta",
    course: "Computer Science",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Passionate about AI and web development. Loves solving real-world problems with code.",
  },
  {
    id: 2,
    name: "Priya Sharma",
    course: "Information Technology",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    description: "Frontend developer who enjoys designing beautiful and responsive user interfaces.",
  },
  {
    id: 3,
    name: "Rohan Patel",
    course: "Electronics and Communication",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    description: "Curious about IoT and embedded systems. Enjoys building small hardware projects.",
  },
  {
    id: 4,
    name: "Sneha Das",
    course: "Data Science",
    image: "https://randomuser.me/api/portraits/women/48.jpg",
    description: "Data enthusiast who loves working with numbers and visualizing insights.",
  },
  {
    id: 5,
    name: "Aditya Singh",
    course: "Software Engineering",
    image: "https://randomuser.me/api/portraits/men/51.jpg",
    description: "Backend developer exploring scalable APIs and cloud services.",
  },
  {
    id: 6,
    name: "Neha Verma",
    course: "Artificial Intelligence",
    image: "https://randomuser.me/api/portraits/women/72.jpg",
    description: "Aspiring ML engineer passionate about NLP and computer vision applications.",
  },
  {
    id: 7,
    name: "Karan Malhotra",
    course: "Cyber Security",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
    description: "Cyber security enthusiast who enjoys ethical hacking and system defense challenges.",
  },
  {
    id: 8,
    name: "Aisha Khan",
    course: "Information Systems",
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    description: "Loves optimizing data flow between systems and building user-focused business dashboards.",
  },
  {
    id: 9,
    name: "Vivek Rao",
    course: "Mechanical Engineering",
    image: "https://randomuser.me/api/portraits/men/66.jpg",
    description: "Tech-savvy mechanical engineer interested in robotics and automation.",
  },
  {
    id: 10,
    name: "Tanya Joshi",
    course: "Cloud Computing",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    description: "Learning about distributed systems and cloud architecture. AWS Certified Practitioner.",
  },
];
